// <auto-generated />
using System;
using LearningQA.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningContextSqlServerMigrations.Migrations
{
    [DbContext(typeof(LearningQAContext))]
    [Migration("20210727104717_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningQA.Shared.Entities.AnswareOption<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Answer<int>Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Answer<int>Id");

                    b.ToTable("AnswareOptions");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Answer<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int?>("QUestionSqlId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Test<QUestionSql, int>Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QUestionSqlId");

                    b.HasIndex("Test<QUestionSql, int>Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Category<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Person<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber")
                        .IsUnique()
                        .HasFilter("[IdNumber] IS NOT NULL");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gilon",
                            Email = "Yos@gmail.com",
                            IdNumber = "135792468",
                            Name = "yosef Levy",
                            Password = "12345@12345",
                            Phone = "+97249984222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gilon",
                            Email = "Yoni@gmail.com",
                            IdNumber = "246813579",
                            Name = "Yoni Levy",
                            Password = "12345@12345",
                            Phone = "+97249984220"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gilon",
                            Email = "Tal@gmail.com",
                            IdNumber = "1502626",
                            Name = "Tal Levy",
                            Password = "12345@12345",
                            Phone = "+97249984226"
                        });
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.QUestionSql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnswerType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestItem<QUestionSql, int>Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestItem<QUestionSql, int>Id");

                    b.ToTable("QUestionSqls");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.QuestionOption<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.Property<int?>("QUestionSqlId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QUestionSqlId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Supplement<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<string>("OriginalContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalcontentType")
                        .HasColumnType("int");

                    b.Property<int?>("QUestionSqlId")
                        .HasColumnType("int");

                    b.Property<int>("RotateContent")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QUestionSqlId");

                    b.ToTable("Supplements");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Test<LearningQA.Shared.Entities.QUestionSql, int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int?>("Person<int>Id")
                        .HasColumnType("int");

                    b.Property<int>("TestItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Person<int>Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.TestItem<LearningQA.Shared.Entities.QUestionSql, int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chapter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExamRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TestQuestionMarking")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Chapter", "Subject", "Version")
                        .IsUnique()
                        .HasFilter("[Category] IS NOT NULL AND [Chapter] IS NOT NULL AND [Subject] IS NOT NULL");

                    b.ToTable("TestItems");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.AnswareOption<int>", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.Answer<int>", null)
                        .WithMany("SelectedAnswer")
                        .HasForeignKey("Answer<int>Id");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Answer<int>", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.QUestionSql", "QUestionSql")
                        .WithMany()
                        .HasForeignKey("QUestionSqlId");

                    b.HasOne("LearningQA.Shared.Entities.Test<LearningQA.Shared.Entities.QUestionSql, int>", null)
                        .WithMany("Answers")
                        .HasForeignKey("Test<QUestionSql, int>Id");

                    b.Navigation("QUestionSql");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.QUestionSql", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.TestItem<LearningQA.Shared.Entities.QUestionSql, int>", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestItem<QUestionSql, int>Id");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.QuestionOption<int>", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.QUestionSql", null)
                        .WithMany("Options")
                        .HasForeignKey("QUestionSqlId");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Supplement<int>", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.QUestionSql", null)
                        .WithMany("Supplements")
                        .HasForeignKey("QUestionSqlId");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Test<LearningQA.Shared.Entities.QUestionSql, int>", b =>
                {
                    b.HasOne("LearningQA.Shared.Entities.Person<int>", null)
                        .WithMany("Tests")
                        .HasForeignKey("Person<int>Id");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Answer<int>", b =>
                {
                    b.Navigation("SelectedAnswer");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Person<int>", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.QUestionSql", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Supplements");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.Test<LearningQA.Shared.Entities.QUestionSql, int>", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LearningQA.Shared.Entities.TestItem<LearningQA.Shared.Entities.QUestionSql, int>", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
